stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: spinner:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: deployment.yaml
    envFrom:
    - sourceName: domain
      sourceKey: domain
      targetKey: domain
branch:
  include:
  - master
notification: {}
