apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spinner-ingress
spec:
  rules:
  - host: spinner.at.damnserver.com
    http:
      paths:
      - path: /
        backend:
          serviceName: spinner-service
          servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: spinner-service
spec:
  selector:
    app: spinner
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinner
  labels:
    app: spinner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinner
  template:
    metadata:
      labels:
        app: spinner
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - spinner
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: spinner
        image: spinner:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
